name: Erweiterter Hello World Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# Definiere Umgebungsvariablen, die im gesamten Workflow verfügbar sind
env:
  GREETING: "Willkommen bei deinem ersten GitHub Actions Workflow!"

jobs:
  hello:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Sage Hallo mit Umgebungsvariable
        run: echo "${{ env.GREETING }}"
      
      - name: Zeige GitHub-Kontext
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Repository: ${{ github.repository }}"
          echo "Runner OS: ${{ runner.os }}"
      
      - name: Zeige Verzeichnisinhalt
        run: ls -la
      
      - name: Erstelle eine Datei
        run: |
          echo "Diese Datei wurde durch GitHub Actions erstellt." > generated-file.txt
          echo "Zeitstempel: $(date)" >> generated-file.txt
      
      - name: Zeige Dateiinhalt
        run: cat generated-file.txt
      
      - name: Speichere die Datei als Artefakt
        uses: actions/upload-artifact@v4
        with:
          name: generated-file
          path: generated-file.txt
